### ISSUE TITLE
First peer-to-peer review of the mobile version of the portfolio

### ISSUE THREAD

**Issue by tkz96** [kosher9/kosher9.github.io#5]
Hello Cedric. 

I have taken a good look at your project and really like how true to the design it is. I have noticed some issues with it that I think need addressing.

In the design, there seems to be a lot of vertical space between the skills in the "About-Myself" section. A suggestion would be to reduce the margin on the top or bottom.

The second issue was that your application was scrolling horizontally. You can try to contain the entire app in one parent container and limit the width of that to the screen's width.

@ciraganenicole suggests that you should avoid using comments in the code as it may make it unreadable and that the class names should be more descriptive instead. My iteration on that comment is that you should use comments conservatively and as detailed as needed.

@d2ndjim suggests that you need to refactor your code to properly indent each line. For eg. if a _p_ tag is inside a _div_, then your code should be something like this:

```
<div class="important">
    <p></p>
</div>
```

instead of 

```
<div class="important">
<p></p>
</div> 
```

Thanks and happy coding!

**Comment by kosher9** [comment]
Hello @tkz96 ,

😮  thank you for your feedback dude. I will work on it.

**Comment by kosher9** [comment]
Thank you for your review guys.
